import React from 'react'

const Services = () => {
    return (
        <div key="1" className="bg-[##333333] text-gray-900 mt-20">
            <div className="container mx-auto px-4 py-12">
                <div className='max-w-3xl mx-auto text-center pb-16 md:pb-16'>
                    <h1 className="text-5xl font-bold mb-6 text-center text-white">Revolutionize Your Research</h1>
                    <p className="text-xl mb-4 text-white ">
                        Our AI tool generates knowledge graphs from research papers, providing you with AI-generated summaries and
                        insights for rapid research. Whether you're a seasoned researcher or just starting out, our tool will
                        revolutionize the way you conduct research.
                    </p>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 ml-10">
                    <div>
                        <h2 className="text-3xl font-semibold mb-4 text-white">Powerful AI Tools</h2>
                        <p className="text-lg mb-8 text-white">
                            Our AI tools analyze research papers and generate knowledge graphs, summaries, and insights. This allows
                            you to quickly understand complex topics and conduct research more efficiently.
                        </p>

                        <div className="bg-gray-100 p-4 rounded-lg mb-3">
                            <h3 className="text-xl font-semibold mb-2">AI-generated summaries</h3>
                            <p className="text-base">
                                Get concise summaries of research papers generated by our AI. Save time and focus on what's important.
                            </p>
                        </div>
                        <div className="bg-gray-100 p-4 rounded-lg mb-3">
                            <h3 className="text-xl font-semibold mb-2">Powerful chatbot</h3>
                            <p className="text-base">
                                Interact with the knowledge graph efficiently. Ask questions and get answers directly from the knowledge
                                graph, making your research process more interactive and engaging.
                            </p>
                        </div>
                        <div className="bg-gray-100 p-4 rounded-lg">
                            <h3 className="text-xl font-semibold mb-2">Automated clustering</h3>
                            <p className="text-base">
                                Deep dive into topics with our AI-powered clustering of research papers. Group related papers together,
                                explore topics in depth and discover new insights that you might have missed otherwise.
                            </p>
                        </div>
                    </div>
                    <div className="flex justify-center items-center">
                        <div className="bg-black rounded-lg p-6 w-full max-w-md">
                            <div className="flex justify-between items-center mb-6">
                                <div className="flex space-x-1">
                                    <div className="w-3 h-3 bg-red-500 rounded-full" />
                                    <div className="w-3 h-3 bg-yellow-400 rounded-full" />
                                    <div className="w-3 h-3 bg-green-500 rounded-full" />
                                </div>
                                <div className="bg-gray-700 rounded-full p-1">
                                    <SearchIcon className="text-white" />
                                </div>
                            </div>
                            <div className="bg-gray-800 rounded-lg p-4 mb-6">
                                <div className="flex items-center justify-between mb-4">
                                    <input
                                        className="bg-transparent border-none text-white placeholder-gray-500 focus:outline-none"
                                        placeholder="Search"
                                        type="text"
                                    />
                                    <div className=" text-white">Search</div>
                                </div>
                                <div className="text-white space-y-2">
                                    <div className="flex justify-between items-center">
                                        <span className="font-bold">2308.09438v1</span>
                                        <div variant="secondary">0.705</div>
                                    </div>
                                    <div className="flex justify-between items-center">
                                        <span className="font-bold">1808.05630v1</span>
                                        <div variant="secondary">0.726</div>
                                    </div>
                                    <div className="flex justify-between items-center">
                                        <span className="font-bold">1911.08973v1</span>
                                        <div variant="secondary">0.726</div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

function SearchIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
        </svg>
    )
}


export default Services